config/routes.rb
Vizyon::Application.routes.draw do
  resources :videos

  resources :categories

  resources :users

  root :to => "homepage#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :videos
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :videos
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  attr_accessible :caption, :category_id, :downloadable, :featured, :link, :share_code, :thumbnail, :title, :user_id, :video_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @videos = Video.where(category_id: params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
    @test= "test"
    @videos = Video.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
.container
  .row
    .cust-span-featured
    - @videos.each do |featureVideo|
      - @video = featureVideo
      .video.mtm.mbm
        .media.fill-width
          - if @video.video_type == "Youtube"
            == <iframe width="1000" height="562" src="http://www.youtube.com/embed/#{@video.share_code}" frameborder="0" allowfullscreen></iframe>
          - else
            == <iframe src="http://player.vimeo.com/video/#{@video.share_code}" width="1000" height="562" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        .full-caption.fill-width
          %h2.titles.tk-futura-pt-condensed #{@video.title}
          %span #{simple_format(@video.caption)}
        .buttons.fill-width.tk-futura-pt-condensed
          = link_to "İndir - yakında", "#"


/ = link_to 'Edit', edit_category_path(@category)
/ \|
/ = link_to 'Back', categories_path

app/views/homepage/index.html.haml
.container
  .row
    .cust-span-featured
      %h1.titles.tk-futura-pt-condensed
        Özel video
      .video.mtm
        .media
          - @featureVideo = @videos.select { |video| video.featured == true } .first

          - if @featureVideo.video_type == "Youtube"
            == <iframe width="590" height="330" src="http://www.youtube.com/embed/#{@featureVideo.share_code}" frameborder="0" allowfullscreen></iframe>
          - else
            == <iframe src="http://player.vimeo.com/video/#{@featureVideo.share_code}" width="590" height="330" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        .caption
          %h2.titles.tk-futura-pt-condensed #{@featureVideo.title}
          %p #{@featureVideo.caption}
        .buttons.tk-futura-pt-condensed
          = link_to "İndir - yakında", "#"

    .cust-span-thumbs
      %h1.titles.tk-futura-pt-condensed
        En son videolar
      .row.mtm
        - @videos.last(6).each do |video|
          -if cycle('odd', 'even') == 'odd'
            %a{:href => "/videos/#{video.id}", :style => "display:block"}
              .thumb.first
                .overlay
                  %h3.titles.tk-futura-pt-condensed
                    = video.title
                %img{:alt => "", :src => "#{video.thumbnail}"}
          -else 
            %a{:href => "/videos/#{video.id}", :style => "display:block"} 
              .thumb
                .overlay
                  %h3.titles.tk-futura-pt-condensed
                    = video.title
                %img{:alt => "", :src => "#{video.thumbnail}"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    %script{:src => "//use.typekit.net/xlz3dab.js", :type => "text/javascript"}
    :javascript
      try{Typekit.load();}catch(e){}

  %body
    .container
      .row
        .span6
          .header.tk-futura-pt-condensed
            = link_to "Vizyonkumru", root_path
        .span6.header-links
          = link_to "Ana sayfa", "/"
          = " :: "
          = link_to "Müzik", "/categories/1"
          = " :: " 
          = link_to "Öğretiş", "/categories/3"
          = " :: "
          = link_to "Kısa Film", "/categories/2"
         
    = yield 

    /= render :partial => "shared/social_code"

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/videos/_form.html.haml
= form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :featured
    = f.check_box :featured
  .field
    = f.label :category_id
    = f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), :prompt => "Select Category"
  .field
    = f.label :video_type
    = f.text_field :video_type
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :caption
    = f.text_area :caption
  .field
    = f.label :share_code
    = f.text_field :share_code
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :thumbnail
    = f.text_field :thumbnail
  / .field
  /   = f.label :downloadable
  /   = f.text_field :downloadable
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit 'Save'

app/views/videos/edit.html.haml
.container
  %h1 Editing video

  = render 'form'

  = link_to 'Show', @video
  \|
  = link_to 'Back', videos_path

app/views/videos/index.html.haml
.container
  .btn.btn-primary.mbm.new-btn
    = link_to 'New Video', new_video_path 
  %h1 Listing videos
  .col12
    %table.table
      %thead
        %tr
          %th User
          %th Category
          %th Title
          %th Type
          //%th Caption
          %th Featured
          %th Link
          %th Video Id
          %th
          %th
      %tbody
        - @videos.each do |video|
          %tr
            %td= video.user.name
            %td= video.category.name
            %td= video.title
            %td= video.video_type
            //%td= video.caption
            %td= video.featured
            %td= video.link
            %td= video.share_code
            %td= link_to 'Show', video
            %td= link_to 'Edit', edit_video_path(video)
            %td= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' }

    %br

app/views/videos/new.html.haml
.container
  %h1 New video

  %form.mbn
    %fieldset
      %div
        %label{:for => "video_input"} Video Url
        %input#video_type{:placeholder => "YouTube or Vimeo:", :name => "video_type"}
        %label{:for => "video_input"} Video Url
        %textarea#video_input{:placeholder => "Paste in a video URL (YouTube or Vimeo)", :name => "video_input"}

  = link_to "Find Video", '#', :class => "btn btn-primary mbm", :id => "btn-find-video"
  
  #videoPreview
  
  #video-details.hide
    = render 'form'

  = link_to 'Back', videos_path


:javascript

  $(document).ready(function() {

    $('#btn-find-video').off().on("click", function(e){
      e.preventDefault();
      if($('#video_type').val().toUpperCase() == "VIMEO"){
        vizyonJs.getVimeoVideo($('#video_input').val());
      }
      else if($('#video_type').val().toUpperCase() == "YOUTUBE"){
        vizyonJs.getYoutubeVideo($('#video_input').val());
      }
      else{
        alert("Not Youtube or Vimeo")
      }
    });


  });

app/views/videos/show.html.haml
.container
  .row
    .video.mtm
      .media.fill-width
        - if @video.video_type == "Youtube"
          == <iframe width="1000" height="562" src="http://www.youtube.com/embed/#{@video.share_code}" frameborder="0" allowfullscreen></iframe>
        - else
          == <iframe src="http://player.vimeo.com/video/#{@video.share_code}" width="1000" height="562" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
      .full-caption.fill-width
        %h2.titles.tk-futura-pt-condensed #{@video.title}
        %span #{simple_format(@video.caption)}
      .buttons.fill-width.tk-futura-pt-condensed
        = link_to "İndir - yakında", "#"

/ = link_to 'Edit', edit_video_path(@video)
/ \|
/ = link_to 'Back', videos_path